'use strict';
(() => {
const C=GameCore,S={...GameStory,...(window.VoiceScenes||{})},$=s=>document.querySelector(s),show=(s,b=true)=>$(s).classList.toggle('hidden',!b),canvas=$('#world'),ctx=canvas.getContext('2d');
if(S.home0_prefix)S.home0=[...S.home0_prefix,...GameStory.home0];
const SAVE='golden-tusk-story-v2',keys=new Set(),images={},sprites={};
let game=new C.Game(),started=false,ready=false,paused=false,dialog=null,mini=null,scene=null,cricket=null,voices={},voice=null;
let width=innerWidth,height=innerHeight,dpr=1,clock=0,last=0,cam={x:1536,y:850,z:.5},toastId,nearest=null,walkPath=[],sound=false,audio=null,musicClock=0,tracked=null,particles=[],lastSave=0;
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastId);toastId=setTimeout(()=>$('#toast').classList.remove('show'),4000);}
function storageRead(){try{return JSON.parse(localStorage.getItem(SAVE));}catch{return null;}}
function save(){if(!started)return;try{localStorage.setItem(SAVE,JSON.stringify(game.snapshot()));$('#saveNote').textContent='Progress saved on this device';}catch{$('#saveNote').textContent='Saving unavailable in this browser';}}
function resize(){width=innerWidth;height=innerHeight;dpr=Math.min(devicePixelRatio||1,2);canvas.width=width*dpr;canvas.height=height*dpr;ctx.imageSmoothingEnabled=false;}
addEventListener('resize',resize);resize();
function load(name,path){return new Promise((resolve,reject)=>{const i=new Image();i.onload=()=>{images[name]=i;resolve();};i.onerror=reject;i.src=path;});}
function spriteTexture(image,x,y,w,h){const c=document.createElement('canvas');c.width=w;c.height=h;const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(image,x,y,w,h,0,0,w,h);const d=g.getImageData(0,0,w,h),p=d.data,seen=new Uint8Array(w*h),queue=[];
 const bg=n=>{const j=n*4;return p[j]>145&&p[j+1]>143&&p[j+2]>112&&Math.abs(p[j]-p[j+1])<38&&p[j+2]<p[j]+18;};const add=n=>{if(n<0||n>=w*h||seen[n])return;seen[n]=1;if(bg(n))queue.push(n);};
 for(let xx=0;xx<w;xx++){add(xx);add((h-1)*w+xx);}for(let yy=0;yy<h;yy++){add(yy*w);add(yy*w+w-1);}for(let q=0;q<queue.length;q++){const n=queue[q];p[n*4+3]=0;if(n%w)add(n-1);if(n%w<w-1)add(n+1);add(n-w);add(n+w);}g.putImageData(d,0,0);return c;}
function prepareSprites(){const xs=[239,337,432,530,627,718,826,923,1025,1121,1220,1320,1427],ys=[87,218,349,482,610,742,872];for(let row=0;row<7;row++)sprites[row]=xs.map(x=>spriteTexture(images.sheet,x-43,ys[row],86,122));[311,493,678,862,1064,1263].forEach((x,i)=>sprites[i+7]=[spriteTexture(images.cast,x-60,620,120,202)]);const a=$('#avatar').getContext('2d');a.imageSmoothingEnabled=false;a.drawImage(sprites[1][0],5,0,50,71);}
function tone(f=440,t=.14,type='triangle',v=.035){if(!sound||!audio)return;const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.value=f;g.gain.setValueAtTime(v,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+t);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+t);}
function toggleSound(){sound=!sound;const AudioCtx=window.AudioContext||window.webkitAudioContext;if(sound&&!audio&&AudioCtx)audio=new AudioCtx();if(sound)audio?.resume();if(!sound)stopVoice();else if(dialog)speak(dialog.key,dialog.index);$('#sound').innerHTML=sound?'♫ <span>Sound on</span>':'♫ <span>Sound off</span>';$('#sound').setAttribute('aria-label',sound?'Mute sound':'Enable sound');tone(523,.2);}
function soundtrack(dt){if(!sound||paused||!started)return;musicClock+=dt;if(musicClock>.55){musicClock=0;const n=[196,246.94,293.66,392,329.63,293.66,246.94,220];tone(n[Math.floor(clock/.55)%8],.3,'sine',dialog?.008:.018);if(Math.floor(clock/.55)%2===0)tone(65,.13,'sine',.05);}}
function stopVoice(){if(voice){voice.onended=null;voice.pause();voice=null;}}
function speak(key,index){stopVoice();const src=voices[key+'.'+String(index+1).padStart(2,'0')];if(src&&sound){const activeDialog=dialog;voice=new Audio(src);voice.onended=()=>setTimeout(()=>{if(sound&&!paused&&dialog===activeDialog&&dialog.index===index)nextLine();},450);voice.play().catch(()=>{});}}
function say(key,done=()=>{},custom){dialog={key,lines:custom||S[key],index:0,done};if(!dialog.lines)throw Error('Missing dialogue '+key);keys.clear();walkPath=[];show('#bubble');show('#cinematic');show('#interactPrompt',false);line();}
function line(){const[n,t]=dialog.lines[dialog.index];$('#bubble .speaker').textContent=n;$('#bubble p').textContent=t;$('#dialogNext').innerHTML='Continue <span>↵</span>';speak(dialog.key,dialog.index);tone(380,.035,'triangle',.012);}
function nextLine(){if(paused||!dialog)return;stopVoice();if(++dialog.index<dialog.lines.length){line();return;}const done=dialog.done;dialog=null;show('#bubble',false);show('#cinematic',false);done();save();}
function refresh(){if(!started)return;const p=game.phase,s=game.state;$('#chapterNo').textContent=s.completed?'STORY COMPLETE · FREE EXPLORATION':`CHAPTER ${String(p.chapter+1).padStart(2,'0')} / 09`;$('#questTitle').textContent=p.title;let objective=p.objective;if(s.phase==='donations')objective+=` ${s.donations.length}/3 visited.`;if(s.phase==='festival')objective+=` ${s.games.length}/3 games played.`;$('#objective').textContent=objective;$('#questStatus').textContent=s.phase==='follow'?'Walk behind him · Keep some distance':s.phase==='approach'?'Avoid the lookouts’ lanterns':'Gold marker: your next objective';$('#day').innerHTML=(night()?'NIGHT 02':p.chapter>=3?'DAY 02':'DAY 01')+' <i>•</i> SHANTI COLONY';$('#inventory').textContent=s.tusk?'Golden tusk · Handle with care':s.rupees?'Mandal fund · ₹'+s.rupees:'One last ball. One big festival.';}
function night(){return game.phase.chapter===6||game.phase.chapter===7;}
function phase(name,pos){game.setPhase(name,pos);keys.clear();walkPath=[];tracked=null;refresh();save();}
function fadeTo(name,pos,label){scene={type:'fade',t:0,duration:2.4,changed:false,next:name,pos};$('#chapterTransition span').textContent=label||'SHANTI COLONY';$('#chapterTransition h2').textContent=C.PHASES[name].title;show('#chapterTransition');keys.clear();}
function start(fresh=false){if(!ready)return;game=new C.Game(fresh?null:storageRead());started=true;paused=false;dialog=mini=scene=cricket=null;keys.clear();walkPath=[];tracked=null;particles=[];stopVoice();if(!audio&&(window.AudioContext||window.webkitAudioContext))toggleSound();['#start','#modal','#minigame','#bubble','#cinematic','#cricketHud','#chapterTransition','#sceneCaption'].forEach(s=>show(s,false));['#quest','#bottom','#touch','#location'].forEach(s=>show(s));cam.x=game.player.x;cam.y=game.player.y;cam.z=1.1;refresh();save();canvas.focus();toast('WASD / arrows to move · E to talk · Click the ground to walk');}
function donorArrival(){phase('donor');const d=game.actor('Mr. Deshmukh'),p=game.point('square');game.goto(d,p.x+70,p.y+50,120);scene={type:'donor',t:0};show('#cinematic');$('#sceneCaption').textContent='Mr. Deshmukh arrives at the mandap';show('#sceneCaption');}
function giveTusk(){game.state.tusk=true;phase('delivery');const p=game.point('square'),d=game.spawn('Mr. Deshmukh',p.x+70,p.y+50);game.goto(d,p.x+360,820,95,true);toast('Received: the golden tusk ornament');}
function robbery(){say('ambush',()=>{game.startChase();refresh();save();toast('After them! Follow the runners to the east lane.');});}
function activityEvents(){for(const e of game.drain()){if(e.type==='phase')refresh();if(e.type==='ambush')robbery();if(e.type==='follow'){toast('Keep behind Deva. Too close and he will spot you.');refresh();}if(e.type==='caught'){keys.clear();walkPath=[];refresh();save();toast(e.reason);}if(e.type==='arrived'){toast('Deva went inside. Reach the window and listen.');refresh();save();}if(e.type==='escaped')say('aftermath',()=>fadeTo('nextday',[1688,680],'THE NEXT MORNING'));}}
function chat(a){const lines={Dada:'Keep your friends close, Rohan. This festival belongs to everyone.',Ayesha:'There is always more to the story than it first seems.',Vikram:'Whatever comes next, we face it together.',Neha:'A few flowers can change the whole square.',Golu:'I am saving my energy for important things. Like modaks.',Ronny:'We have a plan. Mostly.',Deva:'I have somewhere to be.',Priya:'There is room for both mandals in this colony.'};say('chat',()=>{},[[a.name,lines[a.name]||'The whole neighbourhood is getting ready for the festival.']]);}
function interact(){if(!started||paused)return;if(dialog)return nextLine();if(cricket)return swing();if(mini)return miniPress();if(scene)return;const s=game.state.phase;if(['follow','chase'].includes(s)){toast(s==='follow'?'Follow quietly. Do not call out to him.':'Keep running! They are heading for the back lane.');return;}const a=game.nearest();if(!a){toast('Get closer to the gold marker, then press E or tap the action button.');return;}const n=a.name;
 if(s==='opening'&&n==='Vikram')return say('opening',startCricket);
 if(s==='join'&&n==='Ronny')return say('join',()=>phase('donations'));
 if(s==='donations'){const i=['Joshi Aunty','Patil Uncle','Mehta Aunty'].indexOf(n);if(i>=0&&!game.state.donations.includes(i))return say('home'+i,()=>{game.collectDonation(i);refresh();save();toast('₹'+[251,501,301][i]+' collected. Thank you!');});}
 if(s==='report'&&n==='Dada')return say('report',donorArrival);
 if(s==='delivery'&&n==='godown'){phase('ambush');return robbery();}
 if(s==='nextday'&&n==='Dada')return say('nextday',()=>phase('investigate'));
 if(s==='investigate'&&n==='Deva'){toast('Let Deva lead the way. Follow without approaching him.');return;}
 if(s==='listen'&&n==='listen')return say('listen',()=>phase('build'));
 if(s==='build'&&n==='Ronny')return say('build',()=>placement('pillars',()=>{game.state.pillars=true;say('built',()=>phase('decorate'));}));
 if(s==='decorate'&&n==='Neha')return say('decorate',()=>placement('decor',()=>{game.state.decorated=true;fadeTo('briefing',[1688,650],'LATER THAT NIGHT');}));
 if(s==='briefing'&&n==='Vikram')return say('briefing',()=>phase('approach'));
 if(s==='approach'&&n==='ladder'){if(game.alert>.2){toast('A lookout is suspicious. Wait out of sight before climbing.');return;}return say('ladder',()=>{scene={type:'climb',t:0,duration:3.2};keys.clear();show('#cinematic');$('#sceneCaption').textContent='Up the ladder. Across the roof. Quietly.';show('#sceneCaption');});}
 if(s==='roof'&&n==='Golu')return say('roof',()=>timing('pull','Everybody, pull!','Wait for the gold zone, then pull together. Three good pulls will free Golu.',3,()=>say('unstuck',()=>phase('search'))));
 if(s==='search'&&n==='chest')return say('chest',()=>sequencePuzzle(()=>{game.state.tusk=true;say('recovered',()=>phase('escape'));}));
 if(s==='escape'&&n==='window')return say('escape',()=>fadeTo('return',[2214,1430],'BACK INTO THE NIGHT'));
 if(s==='return'&&n==='godown'){phase('truth');game.state.tusk=false;return say('store',()=>say('truth',()=>fadeTo('invite',[2520,810],'THE MORNING OF CHATURTHI')));}
 if(s==='truth'&&n==='Dada')return say('truth',()=>phase('invite'));
 if(s==='invite'&&n==='Deva')return say('invite',()=>{scene={type:'invitation',t:0,duration:2.6};const p=game.point('square');for(const a of game.actors.filter(a=>['Deva','Manav','Priya'].includes(a.name)))game.goto(a,p.x,p.y+150,130,true);show('#cinematic');$('#sceneCaption').textContent='Two mandals. One invitation.';show('#sceneCaption');});
 if(s==='celebrate'&&n==='Dada')return say('celebrate',()=>phase('festival'));
 if(s==='festival'||s==='complete'){
  if(n==='Neha')return rhythm(()=>wonFestival('dhol'));
  if(n==='Golu')return modaks(()=>wonFestival('modak'));
  if(n==='Ronny')return placement('rangoli',()=>wonFestival('flowers'));
  if(n==='Vikram'&&s==='complete'){toast('Vikram sets up one more delivery.');return startCricket(true);}
  if(n==='Dada'){if(game.state.games.length===3)return say('ending',finish);toast('Join all three games first: Neha’s dhol, Golu’s modaks, and Ronny’s flowers.');return;}
 }return chat(a);}
function wonFestival(kind){game.festivalWin(kind);refresh();save();toast('Festival stamp earned · '+game.state.games.length+' / 3');}
function finish(){game.state.completed=true;phase('complete');particles=Array.from({length:150},()=>({x:1350+Math.random()*650,y:280+Math.random()*500,c:['#e7c362','#f7a078','#b3d7a0'][Math.floor(Math.random()*3)],speed:18+Math.random()*30}));menu('ending');}
function startCricket(replay=false){const p=game.point('crease');if(replay)phase('opening',[p.x,p.y]);game.player.x=p.x;game.player.y=p.y;game.player.dir='up';walkPath=[];cricket={t:0,stage:'windup',hit:false,replay,attempts:0};show('#cricketHud');show('#quest',false);$('#cricketHud h2').textContent='The bowler is running in…';$('#swing').disabled=true;show('#cinematic');}
function swing(){if(paused||!cricket||cricket.stage!=='delivery')return;const c=cricket,progress=c.t/1.5;c.attempts++;c.hit=progress>=.60&&progress<=.82;c.stage=c.hit?'shot':'miss';c.t=0;if(c.hit){for(const a of game.actors.filter(a=>a.name.startsWith('Fielder'))){const p=game.point('crease');game.goto(a,p.x+300,p.y-100,135);}}$('#swing').disabled=true;$('#cricketHud h2').textContent=c.hit?'SIX! Into the crowd!':'Not quite. Another delivery!';tone(c.hit?784:130,.25,'triangle',.12);}
function updateCricket(dt){if(!cricket)return;const c=cricket;c.t+=dt;const b=game.actor('Vikram'),p=game.point('crease');if(c.stage==='windup'){if(b){b.y=p.y-180+c.t*25;b.walking=true;}if(c.t>=1.6){c.stage='delivery';c.t=0;$('#swing').disabled=false;$('#cricketHud h2').textContent='Watch the ball. Time your shot.';}}else if(c.stage==='delivery'){$('#cricketHud .needle').style.left=C.clamp(c.t/1.5*100,0,99)+'%';if(c.t>1.5){c.stage='miss';c.t=0;$('#swing').disabled=true;$('#cricketHud h2').textContent='Let that one go? Try again.';}}else if(c.stage==='miss'&&c.t>1.2){c.stage='windup';c.t=0;$('#cricketHud h2').textContent='Here comes the next ball…';}else if(c.stage==='shot'&&c.t>2.6){const replay=c.replay;cricket=null;show('#cricketHud',false);show('#cinematic',false);show('#quest');if(replay){phase('complete',[1688,680]);toast('Another six for the colony!');}else say('six',()=>phase('join'));}}
function baseMini(kind,title,help,button,done){mini={kind,t:0,hits:0,attempts:0,cooldown:.6,done,complete:false};keys.clear();walkPath=[];$('#miniEyebrow').textContent='TOGETHER, WE MAKE IT HAPPEN';$('#miniTitle').textContent=title;$('#miniHelp').textContent=help;$('#miniFeedback').textContent='';$('#miniAction').textContent=button;$('#miniAction').disabled=false;show('#miniAction',!!button);show('#minigame');return mini;}
function closeMini(){const cb=mini.done;mini=null;show('#minigame',false);cb();save();}
function timing(kind,title,help,need,done){const m=baseMini(kind,title,help,kind==='pull'?'PULL TOGETHER':'BEAT THE DHOL',done);m.need=need;m.speed=kind==='pull'?1.9:2.6;m.t=-Math.PI/(2*m.speed);$('#miniContent').innerHTML=(kind==='dhol'?'<div class="beat-lights">'+Array.from({length:need},()=>'<span></span>').join('')+'</div>':'<div class="team-pull">Rohan + Vikram + Ronny <strong>← Golu</strong></div>')+'<div class="timing-track"><div class="sweet"></div><div class="needle"></div></div><div class="score">0 / '+need+' successful beats</div>';}
function rhythm(done){timing('dhol','Bring the dhol to life','Press Space or tap the drum when the marker reaches the gold zone. Land eight beats with the whole mandal.',8,done);}
function miniPress(){if(!mini||mini.complete||paused)return;const m=mini;if(m.kind==='placement'){if(m.placed.size===m.count)closeMini();return;}if(!['pull','dhol'].includes(m.kind)||m.cooldown>0)return;m.cooldown=.32;m.attempts++;const pos=(Math.sin(m.t*m.speed)+1)/2;if(pos>=.4&&pos<=.6){m.hits++;tone(m.kind==='pull'?523:85,.2,'triangle',.1);$('#miniFeedback').textContent=m.kind==='pull'?'Together! A little further…':'Right on the beat!';if(m.kind==='dhol')document.querySelectorAll('.beat-lights span')[m.hits-1].classList.add('on');}else{$('#miniFeedback').textContent=pos<.4?'A little early. Wait for the centre.':'A little late. Try the next pass.';tone(140,.1);}$('.score').textContent=`${m.hits} / ${m.need} successful beats`;if(m.hits===m.need){m.complete=true;m.endAt=m.t+.8;$('#miniAction').disabled=true;}}
function placement(type,done){const labels=type==='pillars'?['Front left pillar','Front right pillar','Back left pillar','Back right pillar']:type==='rangoli'?['Marigold centre','White petals','Red petals','Green leaves','Golden border','Festival lamp']:['Arch garland','Left flowers','Right flowers','Entrance lamp','Stage flowers','Festival bunting'];const m=baseMini('placement',type==='pillars'?'Build the mandap frame':type==='rangoli'?'Flowers for everyone':'A mandap full of colour','Drag each piece to its matching position. On a phone, tap a piece, then tap its place.','ADMIRE YOUR WORK',done);m.placed=new Set();m.selected=null;m.count=labels.length;show('#miniAction',false);const order=labels.length===4?[2,0,3,1]:[3,0,4,1,5,2];$('#miniContent').innerHTML='<div class="decor-grid '+(labels.length===4?'four':'')+'">'+labels.map((n,i)=>`<button class="decor-slot" data-slot="${i}">${n}<small>Place here</small></button>`).join('')+'</div><div class="piece-tray">'+order.map(i=>`<button class="decor-piece" draggable="true" data-piece="${i}">${labels[i]}</button>`).join('')+'</div>';
 const place=(i,j)=>{if(i===null||m.placed.has(i))return;if(i!==j){$('#miniFeedback').textContent='That piece belongs in another position.';return;}m.placed.add(i);const slot=$(`[data-slot="${j}"]`);slot.classList.add('filled');slot.textContent='✓ '+labels[j];$(`[data-piece="${i}"]`).disabled=true;$(`[data-piece="${i}"]`).classList.add('used');m.selected=null;tone(523+j*50,.15);$('#miniFeedback').textContent=m.placed.size+' / '+labels.length+' placed';if(m.placed.size===labels.length){show('#miniAction');$('#miniFeedback').textContent='Beautiful. Everyone helped make this happen.';}};
 document.querySelectorAll('[data-piece]').forEach(el=>{el.onclick=()=>{m.selected=+el.dataset.piece;document.querySelectorAll('[data-piece]').forEach(b=>b.classList.toggle('selected',b===el));};el.ondragstart=e=>{m.selected=+el.dataset.piece;e.dataTransfer.setData('text/plain',el.dataset.piece);};});document.querySelectorAll('[data-slot]').forEach(el=>{el.onclick=()=>place(m.selected,+el.dataset.slot);el.ondragover=e=>e.preventDefault();el.ondrop=e=>{e.preventDefault();place(m.selected,+el.dataset.slot);};});}
function sequencePuzzle(done){const m=baseMini('latches','The ornament chest','Ronny remembers the wrapping: flower, lamp, flower. Open the three latches in that order.','',done);m.sequence=[0,1,0];m.index=0;$('#miniContent').innerHTML='<div class="latches"><span>○</span><span>○</span><span>○</span></div><div class="menu-buttons centered"><button class="secondary" data-symbol="0">✿ Flower</button><button class="secondary" data-symbol="1">♨ Lamp</button><button class="secondary" data-symbol="2">◇ Diamond</button></div>';document.querySelectorAll('[data-symbol]').forEach(b=>b.onclick=()=>{if(paused||m.complete)return;if(+b.dataset.symbol===m.sequence[m.index]){$('.latches').children[m.index].textContent='●';m.index++;tone(440+m.index*100,.15);if(m.index===3){m.complete=true;m.endAt=m.t+.8;$('#miniFeedback').textContent='The chest opens. The golden tusk is safe.';}}else{m.index=0;document.querySelectorAll('.latches span').forEach(e=>e.textContent='○');$('#miniFeedback').textContent='The latches reset. Flower, lamp, flower.';tone(120,.12);}});}
function modaks(done){const m=baseMini('modak','Golu’s modak mission','Watch the serving order, then repeat it. Three rounds. A mistake just gives Golu an excuse to taste another one.','',done);m.round=0;m.index=0;m.sequence=[];$('#miniContent').innerHTML='<div class="modak-board">'+['Classic','Saffron','Coconut','Jaggery'].map((n,i)=>`<button class="modak-pad" data-pad="${i}"><strong>${['①','②','③','④'][i]}</strong>${n}</button>`).join('')+'</div><div class="score">Round 1 / 3</div>';m.next=()=>{m.sequence=Array.from({length:m.round+3},(_,i)=>(i*3+m.round+1)%4);m.index=0;m.showTime=0;m.stage='show';$('#miniFeedback').textContent='Watch the order…';};m.next();document.querySelectorAll('[data-pad]').forEach(b=>b.onclick=()=>{if(paused||m.stage!=='repeat'||m.complete)return;const i=+b.dataset.pad;tone(330+i*100,.16);if(i!==m.sequence[m.index]){$('#miniFeedback').textContent='One more taste. Watch the order again.';m.stage='retry';m.retryAt=m.t+1;return;}m.index++;if(m.index===m.sequence.length){m.round++;$('.score').textContent='Round '+Math.min(3,m.round+1)+' / 3';if(m.round===3){m.complete=true;m.endAt=m.t+.8;$('#miniFeedback').textContent='Perfect! There is a modak for everyone.';}else m.next();}});}
function updateMini(dt){if(!mini)return;const m=mini;m.t+=dt;m.cooldown=Math.max(0,m.cooldown-dt);if(m.complete){if(m.t>=m.endAt)closeMini();return;}if(['pull','dhol'].includes(m.kind))$('.needle').style.left=((Math.sin(m.t*m.speed)+1)/2*99)+'%';if(m.kind==='modak'){if(m.stage==='show'){m.showTime+=dt;const step=Math.floor(m.showTime/.8),on=m.showTime%.8<.55;document.querySelectorAll('[data-pad]').forEach(b=>b.classList.toggle('lit',on&&+b.dataset.pad===m.sequence[step]));if(step>=m.sequence.length){m.stage='repeat';$('#miniFeedback').textContent='Your turn! Repeat the serving order.';}}else if(m.stage==='retry'&&m.t>m.retryAt)m.next();}}
function updateScene(dt){if(!scene)return;const s=scene;s.t+=dt;if(s.type==='fade'){if(s.t>1&&!s.changed){s.changed=true;phase(s.next,s.pos);}if(s.t>s.duration){scene=null;show('#chapterTransition',false);}}else if(s.type==='donor'){const a=game.actor('Mr. Deshmukh');if((a&&a.route.length===0)||s.t>10){scene=null;show('#sceneCaption',false);show('#cinematic',false);say('donor',giveTusk);}}else if(s.type==='climb'&&s.t>s.duration){scene=null;show('#sceneCaption',false);show('#cinematic',false);phase('roof',[350,700]);say('roof',()=>timing('pull','Operation: unstuck','Pull when the marker is in the gold zone. Three pulls, together.',3,()=>say('unstuck',()=>phase('search'))));}else if(s.type==='invitation'&&s.t>s.duration){scene=null;show('#sceneCaption',false);show('#cinematic',false);fadeTo('celebrate',[1688,710],'BAPPA ARRIVES · THE WHOLE COLONY GATHERS');}}
function menu(type='pause'){if(!started)return;paused=true;keys.clear();game.player.walking=false;stopVoice();show('#modal');const el=$('#modalContent');if(type==='journal'){el.innerHTML='<div class="eyebrow">ROHAN’S JOURNAL</div><h2>A festival to remember</h2><p>'+game.phase.objective+'</p><ol class="chapter-list">'+C.CHAPTERS.map((c,i)=>`<li class="${game.state.completed||i<game.phase.chapter?'done':i===game.phase.chapter?'current':''}"><span>${game.state.completed||i<game.phase.chapter?'✓':String(i+1).padStart(2,'0')}</span>${c}</li>`).join('')+'</ol><p>Mandal fund: ₹'+game.state.rupees+' · Festival games: '+game.state.games.length+'/3</p>';}
 else if(type==='map'){const map=game.state.map,points=map==='hideout'?{window:game.points.window,chest:game.points.chest}:{'Cricket ground':game.points.crease,'Mandap square':game.points.square,'Godown':game.points.godown,'Residential lane':[750,1410],'Rival hideout':game.points.ladder},m=C.MAPS[map];el.innerHTML='<div class="eyebrow">YOUR NEIGHBOURHOOD</div><h2>'+ (map==='hideout'?'Inside the hideout':'Shanti Colony')+'</h2><div class="map-panel '+(map==='hideout'?'interior':'')+'">'+Object.entries(points).map(([name,p])=>`<button class="map-label" data-map="${name}" style="left:${p[0]/m.width*100}%;top:${p[1]/m.height*100}%">${name}</button>`).join('')+`<span class="map-dot" style="left:${game.player.x/m.width*100}%;top:${game.player.y/m.height*100}%"></span></div><p>White dot: you. Choose a location to follow a walking route. Take over with WASD at any time.</p>`;document.querySelectorAll('[data-map]').forEach(b=>b.onclick=()=>{const p=points[b.dataset.map];tracked={x:p[0],y:p[1],name:b.dataset.map};if(!dialog&&!mini&&!scene&&!cricket&&!['follow','chase','approach'].includes(game.state.phase))walkPath=C.path(game.player,tracked,game.state.map);closeMenu();toast('Tracking '+b.dataset.map);});}
 else if(type==='restart'){el.innerHTML='<div class="eyebrow">BEGIN AGAIN</div><h2>A new adventure?</h2><p>This replaces your saved story on this device.</p><div class="menu-buttons"><button class="primary" id="confirmRestart">Start a new story</button><button class="secondary" id="resume">Keep my progress</button></div>';$('#confirmRestart').onclick=()=>start(true);$('#resume').onclick=closeMenu;}
 else if(type==='ending'){el.innerHTML='<div class="eyebrow">MANDALA · THE END</div><h2>One colony.<br>One big family.</h2><p>The ornament came home. Two mandals found each other. And Rohan learned that courage also means telling the truth.</p><div class="stat-row"><div><strong>9</strong><span>chapters</span></div><div><strong>₹'+game.state.rupees+'</strong><span>raised together</span></div><div><strong>3</strong><span>festival games</span></div></div><div class="credits">Rohan · Vikram · Ayesha · Dada · Neha · Golu · Ronny<br>Deva · Manav · Aadi · Sameer · Ishant · Priya<br><br>Story and character designs provided by you.<br>Original colony and hideout artwork created for this game.<br>Original recorded performances + synthetic Hindi voices.<br>English subtitles throughout.<br><br>Ganpati Bappa Morya!</div><div class="menu-buttons"><button class="primary" id="resume">Keep celebrating</button><button class="secondary" id="restart">Play the story again</button></div>';$('#resume').onclick=closeMenu;$('#restart').onclick=()=>menu('restart');}
 else{save();el.innerHTML='<div class="eyebrow">TAKE A BREATHER</div><h2>The colony can wait.</h2><p>WASD / arrow keys to walk. E to talk or inspect. Space for timing games. Click the ground to walk there, or choose a route on the map.</p><p>On Android, use the direction pad and the gold action button. Landscape gives you a wider view.</p><p>Your progress saves in this browser on this device. Pausing freezes chases and mini-games too.</p><div class="menu-buttons"><button class="primary" id="resume">Continue adventure</button><button class="secondary" id="menuJournal">Journal</button><button class="secondary" id="checkpoint">Return to checkpoint</button><button class="secondary" id="restart">Start again</button></div>';$('#resume').onclick=closeMenu;$('#menuJournal').onclick=()=>menu('journal');$('#restart').onclick=()=>menu('restart');$('#checkpoint').onclick=()=>{startFrom(game.snapshot());toast('Back at a safe story checkpoint.');};}}
function startFrom(s){stopVoice();game=new C.Game(s);paused=false;dialog=mini=scene=cricket=null;walkPath=[];keys.clear();['#modal','#minigame','#bubble','#cinematic','#cricketHud','#sceneCaption','#chapterTransition'].forEach(s=>show(s,false));show('#quest');refresh();save();}
function closeMenu(){show('#modal',false);paused=false;keys.clear();if(dialog)speak(dialog.key,dialog.index);canvas.focus();}
function worldToScreen(x,y){return{x:(x-cam.x)*cam.z+width/2,y:(y-cam.y)*cam.z+height/2};}
function drawCharacter(a){const frames=sprites[a.sprite??C.CAST[a.name]??1];if(!frames)return;let frame=0,flip=false;const step=a.walking?Math.floor(clock*9)%3:0;if(frames.length>1){if(a.dir==='up')frame=3+(step===1?2:0);else if(a.dir==='left'||a.dir==='right'){frame=8+step;flip=a.dir==='left';}else frame=step;}else flip=a.dir==='left';const sprite=frames[Math.min(frame,frames.length-1)],size=game.state.map==='hideout'?80:78;ctx.save();ctx.translate(a.x,a.y);const bob=a.mode==='dance'?Math.sin(clock*5+(a.seed||0))*5:a.walking?Math.sin(clock*18)*1.7:Math.sin(clock*1.7+a.x)*.5;ctx.fillStyle='#10291970';ctx.beginPath();ctx.ellipse(0,0,20,6,0,0,Math.PI*2);ctx.fill();if(flip)ctx.scale(-1,1);if(a.name==='Mr. Deshmukh')ctx.filter='sepia(.45) brightness(1.3)';ctx.drawImage(sprite,-26,-size+bob,52,size);ctx.filter='none';if(a.name==='Rohan'&&game.state.tusk){ctx.fillStyle='#e9c776';ctx.fillRect(14,-39,18,12);ctx.strokeStyle='#6e4821';ctx.lineWidth=2;ctx.strokeRect(14,-39,18,12);}if(a.mode==='work'&&!a.walking){ctx.strokeStyle='#deb166';ctx.lineWidth=4;ctx.beginPath();ctx.moveTo(15,-25);ctx.lineTo(28+Math.sin(clock*4)*4,-35);ctx.stroke();}ctx.restore();}
function marker(a,color='#ffdf8a'){const p=4*Math.sin(clock*3);ctx.fillStyle=color;ctx.strokeStyle='#203b2b';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(a.x,a.y-105+p);ctx.lineTo(a.x+9,a.y-94+p);ctx.lineTo(a.x,a.y-83+p);ctx.lineTo(a.x-9,a.y-94+p);ctx.closePath();ctx.fill();ctx.stroke();}
function worldDecor(){if(game.state.map==='hideout'){if(game.state.tusk){ctx.fillStyle='#181715ee';ctx.fillRect(1140,60,146,105);ctx.fillStyle='#d4bd81';ctx.font='15px Georgia';ctx.textAlign='center';ctx.fillText('Ornament secured',1212,190);}return;}const p=game.point('square');if(game.state.pillars){for(const dx of[-220,220]){ctx.fillStyle='#e4c190';ctx.fillRect(p.x+dx-8,270,16,80);ctx.fillStyle='#916530';ctx.fillRect(p.x+dx-15,337,30,10);}}
 if(game.state.decorated){for(let i=0;i<22;i++){const x=p.x-250+i*24,y=340+Math.sin(i/21*Math.PI)*45;ctx.fillStyle=i%2?'#eac66d':'#ef9d4e';ctx.beginPath();ctx.arc(x,y,6,0,Math.PI*2);ctx.fill();if(night()||game.phase.chapter>=8){const g=ctx.createRadialGradient(x,y,0,x,y,24);g.addColorStop(0,'#ffd67d60');g.addColorStop(1,'#ffd67d00');ctx.fillStyle=g;ctx.fillRect(x-24,y-24,48,48);}}}if(game.phase.chapter===8&&images.murti)ctx.drawImage(images.murti,p.x-115,95,230,260);
 if(game.state.phase==='approach')for(const a of game.actors.filter(a=>a.mode==='guard')){const angle={down:Math.PI/2,up:-Math.PI/2,left:Math.PI,right:0}[a.dir];ctx.fillStyle='#f8d89030';ctx.beginPath();ctx.moveTo(a.x,a.y);ctx.arc(a.x,a.y,185,angle-.65,angle+.65);ctx.closePath();ctx.fill();}}
function cricketRender(){if(!cricket)return;const c=cricket,p=game.point('crease');let x=p.x,y=p.y-160,z=0;if(c.stage==='delivery'){const v=c.t/1.5;y=p.y-160+v*210;z=Math.abs(Math.sin(v*Math.PI*2))*15;}if(c.stage==='shot'){const v=Math.min(c.t/2,1);x=p.x+v*500;y=p.y-v*240;z=Math.sin(v*Math.PI)*160;ctx.strokeStyle='#fff1b899';ctx.lineWidth=2;ctx.setLineDash([7,6]);ctx.beginPath();ctx.moveTo(p.x,p.y-30);ctx.quadraticCurveTo(p.x+250,p.y-300,x,y-z);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#fff1b7';ctx.textAlign='center';ctx.font='bold 52px Georgia';ctx.fillText('6',p.x,p.y-160);}if(['delivery','shot'].includes(c.stage)){ctx.fillStyle='#382d2644';ctx.beginPath();ctx.ellipse(x,y,5,2,0,0,Math.PI*2);ctx.fill();ctx.fillStyle='#f0e7cf';ctx.strokeStyle='#6f3928';ctx.lineWidth=1;ctx.beginPath();ctx.arc(x,y-z-22,5,0,Math.PI*2);ctx.fill();ctx.stroke();}ctx.save();ctx.translate(p.x+15,p.y-22);ctx.rotate(c.stage==='shot'?Math.min(c.t*8,2.5)-1.8:.3);ctx.fillStyle='#c39254';ctx.fillRect(-4,-43,10,34);ctx.fillStyle='#463828';ctx.fillRect(-2,-10,5,17);ctx.restore();}
function render(dt){ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);if(!ready)return;const m=started?C.MAPS[game.state.map]:C.MAPS.colony;let target=started?game.player:{x:1560,y:820};if(cricket)target={x:game.points.crease[0]+30,y:game.points.crease[1]-65};if(scene?.type==='donor'){const a=game.actor('Mr. Deshmukh');if(a)target={x:(a.x+game.player.x)/2,y:(a.y+game.player.y)/2};}if(dialog){const n=dialog.lines[dialog.index][0],a=game.actor(n)||game.player;target={x:(a.x+game.player.x)/2,y:(a.y+game.player.y)/2-90};}let zoom=started?(width<700?1.02:1.12):Math.max(width/m.width,height/m.height)*1.02;if(dialog)zoom*=1.14;if(cricket)zoom=width<700?.74:1.1;cam.z+=(zoom-cam.z)*Math.min(1,dt*4);const hx=width/2/cam.z,hy=height/2/cam.z;const tx=m.width<hx*2?m.width/2:C.clamp(target.x,hx,m.width-hx),ty=m.height<hy*2?m.height/2:C.clamp(target.y,hy,m.height-hy);cam.x+=(tx-cam.x)*Math.min(1,dt*6);cam.y+=(ty-cam.y)*Math.min(1,dt*6);ctx.save();ctx.translate(width/2-cam.x*cam.z,height/2-cam.y*cam.z);ctx.scale(cam.z,cam.z);ctx.drawImage(game.state.map==='hideout'&&started?images.interior:images.map,0,0,m.width,m.height);
 if(started){if(night()&&game.state.map==='colony'){ctx.fillStyle='#0715366d';ctx.fillRect(0,0,m.width,m.height);}worldDecor();if(walkPath.length){ctx.strokeStyle='#ffe4a05e';ctx.lineWidth=3;ctx.setLineDash([4,12]);ctx.beginPath();ctx.moveTo(game.player.x,game.player.y);walkPath.forEach(p=>ctx.lineTo(p.x,p.y));ctx.stroke();ctx.setLineDash([]);}[...game.actors,game.player].sort((a,b)=>a.y-b.y).forEach(drawCharacter);cricketRender();if(!dialog&&!scene&&!cricket){game.targets().forEach(a=>marker(a));if(tracked)marker(tracked,'#fff');}particles.forEach(p=>{p.y+=p.speed*dt;if(p.y>900)p.y=240;ctx.fillStyle=p.c;ctx.fillRect(p.x+Math.sin(clock+p.x)*10,p.y,4,7);});if(scene?.type==='climb'){const p=game.point('ladder'),progress=Math.min(scene.t/scene.duration,1);drawCharacter({...game.player,x:p.x,y:p.y-progress*120,dir:'up',walking:true});}}ctx.restore();if(started){drawCompass();positionUI();}}
function drawCompass(){if(dialog||mini||scene||cricket)return;const a=tracked||game.targets()[0];if(!a)return;const p=worldToScreen(a.x,a.y);if(p.x>40&&p.x<width-40&&p.y>120&&p.y<height-120)return;const angle=Math.atan2(p.y-height/2,p.x-width/2),r=Math.min(width*.38,height*.30),x=width/2+Math.cos(angle)*r,y=height/2+Math.sin(angle)*r;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.fillStyle='#ffdf8a';ctx.strokeStyle='#243b2c';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(14,0);ctx.lineTo(-7,-9);ctx.lineTo(-3,0);ctx.lineTo(-7,9);ctx.closePath();ctx.fill();ctx.stroke();ctx.restore();ctx.fillStyle='#182f24e8';ctx.fillRect(x-24,y+17,48,19);ctx.fillStyle='#fff0c5';ctx.textAlign='center';ctx.font='10px sans-serif';ctx.fillText(Math.round(C.dist(game.player,a)/10)+' m',x,y+30);}
function positionUI(){if(dialog){const a=game.actor(dialog.lines[dialog.index][0])||game.player,p=worldToScreen(a.x,a.y-90),b=$('#bubble'),bw=b.offsetWidth,bh=b.offsetHeight;b.style.left=C.clamp(p.x,bw/2+12,width-bw/2-12)+'px';b.style.top=C.clamp(p.y,bh+90,height-35)+'px';}const available=nearest&&!paused&&!dialog&&!mini&&!scene&&!cricket&&!['follow','chase'].includes(game.state.phase);show('#interactPrompt',!!available);if(available){const p=worldToScreen(nearest.x,nearest.y+32),b=$('#interactPrompt');b.style.left=C.clamp(p.x,110,width-110)+'px';b.style.top=C.clamp(p.y,100,height-140)+'px';const names={ladder:'Climb the ladder',listen:'Listen quietly',chest:'Inspect ornaments',window:'Climb out',godown:'Enter the godown'};b.querySelector('span').textContent=names[nearest.name]||'Talk to '+nearest.name;}const stealth=['follow','approach'].includes(game.state.phase)&&!dialog;show('#alertMeter',stealth);if(stealth){$('#alertMeter i').style.width=Math.min(100,game.alert/(game.state.phase==='follow'?3.5:2.4)*100)+'%';$('#alertLabel').textContent=game.alert>.5?'Careful — you are drawing attention':'Stay quiet · Keep your distance';}$('#location').textContent=game.state.map==='hideout'?'INSIDE THE HIDEOUT':game.player.y>1300?'THE BACK LANES':game.player.x<1200&&game.player.y<720?'CRICKET GROUND':game.player.x>2100?'EAST COLONY':'MANDAP SQUARE';}
function update(dt){if(!paused){clock+=dt;if(started){const busy=!!(dialog||mini||scene||cricket);game.tick(dt,!busy);if(!busy){let dx=0,dy=0;if(keys.has('a')||keys.has('arrowleft'))dx=-1;if(keys.has('d')||keys.has('arrowright'))dx=1;if(!dx){if(keys.has('w')||keys.has('arrowup'))dy=-1;if(keys.has('s')||keys.has('arrowdown'))dy=1;}if(dx||dy)walkPath=[];if(!dx&&!dy&&walkPath.length){const p=walkPath[0],d=C.dist(game.player,p),step=Math.min(d,230*dt);if(d<3){walkPath.shift();game.player.walking=false;}else{const nx=game.player.x+(p.x-game.player.x)/d*step,ny=game.player.y+(p.y-game.player.y)/d*step;game.player.dir=Math.abs(p.x-game.player.x)>Math.abs(p.y-game.player.y)?p.x>game.player.x?'right':'left':p.y>game.player.y?'down':'up';if(C.walkable(nx,ny,game.state.map)){game.player.x=nx;game.player.y=ny;game.player.walking=true;}else{walkPath=C.path(game.player,walkPath[walkPath.length-1],game.state.map);}}}else game.move(dx,dy,dt);nearest=game.nearest();activityEvents();}else game.player.walking=false;updateScene(dt);updateCricket(dt);updateMini(dt);lastSave+=dt;if(lastSave>5&&!busy){lastSave=0;save();}}soundtrack(dt);}render(paused?0:dt);}
function loop(now){const dt=Math.min((now-last)/1000,.04);last=now;update(dt);requestAnimationFrame(loop);}
function action(){if(paused)return;if(dialog)nextLine();else if(cricket)swing();else if(mini)miniPress();else interact();}
addEventListener('keydown',e=>{const k=e.key.toLowerCase();if([' ','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();if(e.repeat)return;if(k==='escape'){if(!started)return;if(paused)closeMenu();else menu();return;}if(paused)return;if(['e','enter',' '].includes(k)){action();return;}if(k==='j'){menu('journal');return;}if(k==='m'){menu('map');return;}keys.add(k);});addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{keys.clear();if(started&&!paused)menu();});document.addEventListener('visibilitychange',()=>{keys.clear();if(document.hidden&&started){save();if(!paused)menu();}});
document.querySelectorAll('[data-dir]').forEach(b=>{const k={up:'w',down:'s',left:'a',right:'d'}[b.dataset.dir];b.onpointerdown=e=>{e.preventDefault();if(paused)return;b.setPointerCapture(e.pointerId);keys.add(k);};b.onpointerup=b.onpointercancel=()=>keys.delete(k);});canvas.onpointerdown=e=>{if(!started||paused||dialog||mini||scene||cricket)return;const p={x:(e.clientX-width/2)/cam.z+cam.x,y:(e.clientY-height/2)/cam.z+cam.y};if(!C.walkable(p.x,p.y,game.state.map))return;walkPath=C.path(game.player,p,game.state.map);};
$('#play').onclick=()=>start();$('#newGame').onclick=()=>{start();menu('restart');};$('#sound').onclick=toggleSound;$('#pause').onclick=()=>paused?closeMenu():menu();$('.wordmark').onclick=e=>{e.preventDefault();menu();};$('#touchAction').onclick=action;$('#dialogNext').onclick=nextLine;$('#miniAction').onclick=miniPress;$('#swing').onclick=swing;$('#journalBtn').onclick=()=>menu('journal');$('#mapBtn').onclick=()=>menu('map');$('#closeModal').onclick=closeMenu;
Promise.all([load('map','assets/colony.png'),load('interior','assets/hideout.png'),load('sheet','assets/mandal-sprites.jpg'),load('cast','assets/characters.jpg'),load('murti','assets/ganesh-murti.png'),fetch('assets/voices.json').then(r=>r.json()).then(d=>voices=d)]).then(()=>{prepareSprites();ready=true;$('#play').disabled=false;$('#play').textContent=storageRead()?'Continue adventure →':'Begin adventure →';show('#newGame',!!storageRead());}).catch(()=>{show('#loadError');$('#play').textContent='Please reload';});requestAnimationFrame(loop);
if(document.modelContext?.registerTool){const life=new AbortController();const valid=input=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('No parameters accepted');};for(const tool of[{name:'read_adventure_progress',description:'Read the current chapter, objective and festival progress without changing the game.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:input=>{valid(input);return{started,chapter:game.phase.chapter+1,phase:game.state.phase,objective:game.phase.objective,completed:game.state.completed,festivalGames:game.state.games.length};}},{name:'open_adventure_journal',description:'Pause the active adventure and open its journal. All active activities are preserved.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:false},execute:input=>{valid(input);if(!started)throw Error('Begin the adventure first');menu('journal');return{opened:true,phase:game.state.phase};}}])try{Promise.resolve(document.modelContext.registerTool(tool,{signal:life.signal})).catch(()=>{});}catch{}addEventListener('pagehide',()=>life.abort());}
})();
