(function(root){'use strict';
const scenes={
 opening:[['Ronny','Rohan! Come on, we have three houses to visit for chanda.'],['Rohan','One ball, Ronny. Just one.'],['Vikram','Six to finish it. Ayesha is watching, by the way.'],['Ayesha','I heard that. Show us the shot, Rohan!']],
 six:[['Vikram','SIX! Over the boundary!'],['Ayesha','All right, that was worth waiting for.'],['Rohan','Now let us get this festival started.']],
 join:[['Ronny','Receipt book, donation box, and one very late batsman. Everyone ready?'],['Golu','Ready. If they offer sweets, I will handle that department.'],['Vikram','First stop: Joshi Aunty. Let Rohan do the talking.']],
 home0:[['Joshi Aunty','Chanda? Ask my husband. He is the finance minister.'],['Patil Uncle','From inside: I resigned this morning!'],['Rohan','Then we are accepting donations from the opposition too.'],['Joshi Aunty','Ha! Here is ₹251. And tell your Golu the modaks are for the festival.'],['Golu','I was only checking their quality.']],
 home1:[['Patil Uncle','I cannot pay today. All my money is in my other trousers.'],['Vikram','Uncle, those are hanging right behind you.'],['Patil Uncle','You children notice too much. Here, ₹501. Put the extra rupee down for luck.'],['Rohan','And your name at the top of the thank-you list.']],
 home2:[['Mehta Aunty','No donations until you settle an important dispute. Who makes better tea, me or my sister?'],['Rohan','For a fair decision, we will need a cup from both of you.'],['Mehta Aunty','Diplomat! Take ₹301, and promise the loud rehearsal starts after breakfast.'],['Ronny','Promise. Golu never starts anything before breakfast anyway.']],
 report:[['Rohan','Dada! Three houses, three stories, and ₹1,053 for the mandal.'],['Dada','Well done. Every rupee came with someone\'s trust. Let us put it to good use.'],['Neha','Dada, Mr. Deshmukh is coming this way.']],
 donor:[['Mr. Deshmukh','Dada, I made a wish to Bappa when my family needed hope. That wish has been fulfilled.'],['Mr. Deshmukh','As promised, I have brought ornaments for the murti. This golden tusk is especially precious to us.'],['Dada','Your gift will be treated with care. Thank you for sharing your happiness with the colony.'],['Rohan','Look at the detail on it!'],['Dada','Rohan, Vikram: take the tusk to our godown. Keep it with the other ornaments until the murti arrives.'],['Rohan','We will put it away safely.']],
 ambush:[['Sameer','Vikram! Remember the money you owe us?'],['Vikram','I said I would pay. This has nothing to do with the mandal.'],['Deva','Then what is in that bundle?'],['Rohan','An ornament for Bappa. Leave it alone.'],['Sameer','We will hold it until your friend pays!'],['Rohan','They took the tusk! Vikram, after them!']],
 aftermath:[['Vikram','They shut the lane behind them. We lost the trail.'],['Rohan','Dada trusted us. What do we tell him?'],['Vikram','Give me tonight. Tomorrow we find it. Please.'],['Rohan','Tomorrow. But we cannot keep this secret forever.']],
 nextday:[['Dada','Good morning! The mandap will not build itself. Ronny, take the pillars. Neha, the flowers.'],['Golu','And me?'],['Dada','Help everyone. Especially when the snacks arrive.'],['Rohan','I will be back in a little while. I need to check something in the east lane.']],
 listen:[['Sameer','They will not celebrate without that ornament. If we do not get our own murti, why should they have everything?'],['Deva','Do not damage it. Put it with the other things in the room.'],['Manav','Someone will find out.'],['Deva','Just keep the door shut.'],['Rohan','So that is why. It was never really about Vikram\'s debt. The tusk is inside, and it is safe.']],
 build:[['Ronny','There you are! Hold this pillar before Golu decides it is a leaning tower.'],['Golu','I call it a bold design choice.'],['Rohan','I will fix the frame. Then there is something I need to tell you all.']],
 built:[['Dada','Solid work. Now the decorations, and tomorrow we welcome Bappa.'],['Vikram','Rohan, you found something, did you not?'],['Rohan','After the lights. Meet me here tonight.']],
 decorate:[['Neha','Garlands across the arch, flowers by the pillars, lamps at the entrance. Make it welcoming.'],['Ayesha','The whole colony should feel at home here.']],
 briefing:[['Rohan','I followed Deva. The tusk is in their old storeroom behind the east lane.'],['Vikram','Then we go together. This started with me.'],['Ronny','There is a ladder around the back. We can reach the window from the roof.'],['Golu','A window. Of course it is a window.'],['Rohan','We take only our tusk and come straight back. Quietly.']],
 ladder:[['Ronny','This is it. One at a time, up the ladder.'],['Vikram','I will check the roof. Rohan, help Golu at the window.'],['Golu','I would like to file a complaint about the size of this window.']],
 roof:[['Golu','I am stuck. Do not laugh.'],['Ronny','Nobody is laughing. Vikram, stop making that face.'],['Rohan','Breathe out. We pull together, on three.']],
 unstuck:[['Golu','I am in! The building can keep my dignity.'],['Vikram','Shh. Find the tusk. Do not touch anything else.']],
 chest:[['Rohan','The wrapping matches Mr. Deshmukh\'s gift. This is the ornament chest.'],['Ronny','Three latches. Remember the marks on the wrapping: flower, lamp, flower.']],
 recovered:[['Rohan','There it is. Not a scratch.'],['Vikram','Thank you. All of you.'],['Golu','Emotional speeches after we get out of the window, please.']],
 escape:[['Ronny','Same way out. Pass me the bundle first.'],['Golu','I am going sideways this time. I have learned things.'],['Rohan','Everyone together. Back to our godown.']],
 store:[['Rohan','Here. With all the other ornaments. Safe at last.'],['Vikram','We actually did it.'],['Dada','Did what, exactly?']],
 truth:[['Dada','Rohan. Vikram. Why are you all here at this hour?'],['Rohan','Dada, we need to tell you everything. The tusk was stolen. We were frightened, so we kept quiet.'],['Vikram','They used my debt as an excuse. Rohan found where they hid it.'],['Rohan','They were angry because their mandal could not celebrate this year. We went in through the roof to get it back.'],['Dada','I am glad you are safe. But next time, tell me before fear makes the decisions for you.'],['Rohan','You are not angry?'],['Dada','Taking it was wrong. We can still choose what happens next. We are all brothers. Invite their whole mandal tomorrow.']],
 invite:[['Rohan','Deva. We have the tusk, and Dada knows what happened.'],['Deva','I knew it. What now?'],['Rohan','He asked me to invite all of you to the celebration.'],['Deva','After what we did? We were jealous. That is no excuse.'],['Priya','Then let us help put things right.'],['Deva','Tell Dada we will be there. And Rohan... I am sorry.']],
 celebrate:[['Dada','Both mandals, under one roof. Now this is a celebration.'],['Mr. Deshmukh','May this happiness reach every home in the colony.'],['Ayesha','A sixer, a mystery, and a whole new group of friends. Busy week, Rohan.'],['Golu','Dhol, flowers, and modaks. Finally, quests I was born for.'],['Dada','Go on. Celebrate together!']],
 ending:[['Deva','Next year, we build the mandap together.'],['Vikram','And settle our debts before the festival.'],['Golu','And make a bigger window.'],['Dada','Ganpati Bappa...'],['Everyone','Morya!']]
};
if(typeof module!=='undefined'&&module.exports)module.exports=scenes;else root.GameStory=scenes;
})(typeof globalThis!=='undefined'?globalThis:this);
